# Generated by Django 4.2.5 on 2023-10-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_userprofile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
