# Generated by Django 4.2.5 on 2023-10-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_userprofile_avatar_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(max_length=20),
        ),
    ]
