# Generated by Django 4.2.5 on 2024-01-02 06:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0012_alter_securitytoken_token_value'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='securitytoken',
            unique_together={('user', 'token_type')},
        ),
    ]
