# Generated by Django 4.2.5 on 2024-01-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_securitytoken_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='Etc/GMT+0', max_length=50),
        ),
    ]
