# Generated by Django 4.2.5 on 2023-09-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='description',
            field=models.CharField(max_length=32),
        ),
    ]
