# Generated by Django 4.2.5 on 2023-09-14 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_initial'),
    ]

    operations = [
    ]
