# Generated by Django 4.2.5 on 2023-09-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20230914_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms_members',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=None),
            preserve_default=False,
        ),
    ]
