# Generated by Django 4.2.5 on 2023-10-09 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='description',
            field=models.TextField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='topic',
            field=models.CharField(default='', max_length=32),
        ),
    ]
