# Generated by Django 4.2.5 on 2023-10-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_rooms_room_name_alter_rooms_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='topic',
            field=models.CharField(default='', max_length=16),
        ),
    ]
