# Generated by Django 4.2.5 on 2023-10-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_rooms_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_name',
            field=models.TextField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='rooms_members',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
