# Generated by Django 4.2.5 on 2023-10-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_rooms_created_at_alter_rooms_room_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='description',
            field=models.TextField(default='', max_length=256, null=True),
        ),
    ]
