# Generated by Django 4.2.5 on 2023-10-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_rooms_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='description',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
