# Generated by Django 4.2.5 on 2023-10-10 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database.rooms'),
            preserve_default=False,
        ),
    ]
