# Generated by Django 4.2.5 on 2023-10-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_messages_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name_plural': 'Messages'},
        ),
    ]
