# Generated by Django 4.2.5 on 2023-10-16 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_messages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='topic',
            field=models.CharField(default='', max_length=20),
        ),
    ]
