# Generated by Django 4.2.5 on 2023-12-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_alter_rooms_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
