# Generated by Django 4.2.5 on 2023-12-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videochat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videochatrooms',
            name='description',
            field=models.TextField(blank=True, default='', max_length=256),
        ),
    ]
