# Generated by Django 4.2.5 on 2023-12-24 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videochat', '0003_alter_videochatrooms_invitation_exp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videochatrooms',
            name='description',
        ),
    ]
